theme = "gruvbox-dark"
icons = "material"

[[block]]
block = "battery"
format = "{percentage}% {time} {power}"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
speed_up = false
speed_down = true
hide_missing = true
hide_inactive = true

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
icons = true
interval = 5

[[block]]
block = "xrandr"

[[block]]
block = "sound"
driver = "auto"

[[block]]
block = "time"
interval = 1 
format = "%Y-%m-%d %R %A"
