theme = "slick"

[icons]
name = "awesome"

# [icons.overrides]
# 
# # Battery
# bat                = "  "
# bat_full           = "  "
# bat_charging       = "  "
# bat_discharging    = "  "
# bat_half           = "  "
# bat_quarter        = "  "
# bat_three_quarters = "  "
# 
# # Backlight
# backlight_full     = "  "
# backlight_partial1 = "  "
# backlight_partial2 = "  "
# backlight_partial3 = "  "
# backlight_empty    = "  "
# 
# # Network
# net_up       = "  "
# net_down     = "  "
# net_wired    = "  "
# net_wireless = " 泌 "
# 
# # Weather
# weather_sun     = " 滛 "
# weather_snow    = " 流 "
# weather_thunder = " 朗 "
# weather_clouds  = " 摒 "
# weather_rain    = " 殺 "
# weather_default = " 摒 "
# 
# # Memory
# memory_mem  = " 勒 "
# memory_swap = " 易 "
# 
# xrandr = "  "
# 
# time = "  "

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°"
service = { name = "openweathermap", api_key = "42a1771a0b787bf12e734ada0cfc80cb", city_id = "1791247", units = "metric" }
interval = 600

[[block]]
block = "memory"
format_mem = "total:{mem_total}, used:{mem_total_used}"
clickable = false

# [[block]]
# block = "sound"
# driver = "auto"

[[block]]
block = "time"
interval = 1 
format = "%Y-%m-%d %R"
