theme = "slick"
icons = "awesome"

[[block]]
block = "battery"
format = "{percentage}% {time} {power}"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
speed_up = false
speed_down = true
hide_missing = true
hide_inactive = true

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°"
service = { name = "openweathermap", api_key = "42a1771a0b787bf12e734ada0cfc80cb", city_id = "1805753", units = "metric" }
interval = 1

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
icons = true
interval = 5

[[block]]
block = "xrandr"

[[block]]
block = "sound"
driver = "auto"

[[block]]
block = "time"
interval = 1 
format = "%Y-%m-%d %R %A"
